cuda_fn!(cuGetErrorString(error: CUresult, pStr: *mut *const c_char) -> CUresult);
cuda_fn!(cuGetErrorName(error: CUresult, pStr: *mut *const c_char) -> CUresult);
cuda_fn!(cuInit(Flags: c_uint) -> CUresult);
cuda_fn!(cuDriverGetVersion(driverVersion: *mut c_int) -> CUresult, {driverVersion});
cuda_fn!(cuDeviceGet(device: *mut CUdevice, ordinal: c_int) -> CUresult, {device});
cuda_fn!(cuDeviceGetCount(count: *mut c_int) -> CUresult, {count});
cuda_fn!(cuDeviceGetName(name: *mut c_char, len: c_int, dev: CUdevice) -> CUresult, {name});
cuda_fn!(cuDeviceGetUuid(uuid: *mut CUuuid, dev: CUdevice) -> CUresult, {uuid});
cuda_fn!(cuDeviceGetUuid_v2(uuid: *mut CUuuid, dev: CUdevice) -> CUresult, {uuid});
cuda_fn!(cuDeviceGetLuid(luid: *mut c_char, deviceNodeMask: *mut c_uint, dev: CUdevice) -> CUresult, {luid, deviceNodeMask});
cuda_fn!(cuDeviceTotalMem_v2(bytes: *mut usize, dev: CUdevice) -> CUresult, {bytes});
cuda_fn!(cuDeviceGetTexture1DLinearMaxWidth(maxWidthInElements: *mut usize, format: CUarray_format, numChannels: c_uint, dev: CUdevice) -> CUresult, {maxWidthInElements});
cuda_fn!(cuDeviceGetAttribute(pi: *mut c_int, attrib: CUdevice_attribute, dev: CUdevice) -> CUresult, {pi});
cuda_fn!(cuDeviceGetNvSciSyncAttributes(nvSciSyncAttrList: *mut c_void, dev: CUdevice, flags: c_int) -> CUresult);
cuda_fn!(cuDeviceSetMemPool(dev: CUdevice, pool: CUmemoryPool) -> CUresult);
cuda_fn!(cuDeviceGetMemPool(pool: *mut CUmemoryPool, dev: CUdevice) -> CUresult);
cuda_fn!(cuDeviceGetDefaultMemPool(pool_out: *mut CUmemoryPool, dev: CUdevice) -> CUresult);
cuda_fn!(cuDeviceGetExecAffinitySupport(pi: *mut c_int, type_: CUexecAffinityType, dev: CUdevice) -> CUresult, {pi});
cuda_fn!(cuFlushGPUDirectRDMAWrites(target: CUflushGPUDirectRDMAWritesTarget, scope: CUflushGPUDirectRDMAWritesScope) -> CUresult);
cuda_fn!(cuDeviceGetProperties(prop: *mut CUdevprop, dev: CUdevice) -> CUresult);
cuda_fn!(cuDeviceComputeCapability(major: *mut c_int, minor: *mut c_int, dev: CUdevice) -> CUresult, {major, minor});
cuda_fn!(cuDevicePrimaryCtxRetain(pctx: *mut CUcontext, dev: CUdevice) -> CUresult, {pctx});
cuda_fn!(cuDevicePrimaryCtxRelease_v2(dev: CUdevice) -> CUresult);
cuda_fn!(cuDevicePrimaryCtxSetFlags_v2(dev: CUdevice, flags: c_uint) -> CUresult);
cuda_fn!(cuDevicePrimaryCtxGetState(dev: CUdevice, flags: *mut c_uint, active: *mut c_int) -> CUresult, {flags, active});
cuda_fn!(cuDevicePrimaryCtxReset_v2(dev: CUdevice) -> CUresult);
cuda_fn!(cuCtxCreate_v2(pctx: *mut CUcontext, flags: c_uint, dev: CUdevice) -> CUresult, {pctx});
cuda_fn!(cuCtxCreate_v3(pctx: *mut CUcontext, paramsArray: *mut CUexecAffinityParam, numParams: c_int, flags: c_uint, dev: CUdevice) -> CUresult, {pctx});
cuda_fn!(cuCtxDestroy_v2(ctx: CUcontext) -> CUresult);
cuda_fn!(cuCtxPushCurrent_v2(ctx: CUcontext) -> CUresult);
cuda_fn!(cuCtxPopCurrent_v2(pctx: *mut CUcontext) -> CUresult, {pctx});
cuda_fn!(cuCtxSetCurrent(ctx: CUcontext) -> CUresult);
cuda_fn!(cuCtxGetCurrent(pctx: *mut CUcontext) -> CUresult, {pctx});
cuda_fn!(cuCtxGetDevice(device: *mut CUdevice) -> CUresult, {device});
cuda_fn!(cuCtxGetFlags(flags: *mut c_uint) -> CUresult, {flags});
cuda_fn!(cuCtxSetFlags(flags: c_uint) -> CUresult);
cuda_fn!(cuCtxGetId(ctx: CUcontext, ctxId: *mut c_ulonglong) -> CUresult, {ctxId});
cuda_fn!(cuCtxSynchronize() -> CUresult);
cuda_fn!(cuCtxSetLimit(limit: CUlimit, value: usize) -> CUresult);
cuda_fn!(cuCtxGetLimit(pvalue: *mut usize, limit: CUlimit) -> CUresult, {pvalue});
cuda_fn!(cuCtxGetCacheConfig(pconfig: *mut CUfunc_cache) -> CUresult, {pconfig});
cuda_fn!(cuCtxSetCacheConfig(config: CUfunc_cache) -> CUresult);
cuda_fn!(cuCtxGetSharedMemConfig(pConfig: *mut CUsharedconfig) -> CUresult, {pConfig});
cuda_fn!(cuCtxSetSharedMemConfig(config: CUsharedconfig) -> CUresult);
cuda_fn!(cuCtxGetApiVersion(ctx: CUcontext, version: *mut c_uint) -> CUresult, {version});
cuda_fn!(cuCtxGetStreamPriorityRange(leastPriority: *mut c_int, greatestPriority: *mut c_int) -> CUresult, {leastPriority, greatestPriority});
cuda_fn!(cuCtxResetPersistingL2Cache() -> CUresult);
cuda_fn!(cuCtxGetExecAffinity(pExecAffinity: *mut CUexecAffinityParam, type_: CUexecAffinityType) -> CUresult);
cuda_fn!(cuCtxAttach(pctx: *mut CUcontext, flags: c_uint) -> CUresult, {pctx});
cuda_fn!(cuCtxDetach(ctx: CUcontext) -> CUresult);
cuda_fn!(cuModuleLoad(module: *mut CUmodule, fname: *const c_char) -> CUresult, {module});
cuda_fn!(cuModuleLoadData(module: *mut CUmodule, image: *const c_void) -> CUresult, {module});
cuda_fn!(cuModuleLoadDataEx(module: *mut CUmodule, image: *const c_void, numOptions: c_uint, options: *mut CUjit_option, optionValues: *mut *mut c_void) -> CUresult, {module});
cuda_fn!(cuModuleLoadFatBinary(module: *mut CUmodule, fatCubin: *const c_void) -> CUresult, {module});
cuda_fn!(cuModuleUnload(hmod: CUmodule) -> CUresult);
cuda_fn!(cuModuleGetLoadingMode(mode: *mut CUmoduleLoadingMode) -> CUresult, {mode});
cuda_fn!(cuModuleGetFunction(hfunc: *mut CUfunction, hmod: CUmodule, name: *const c_char) -> CUresult, {hfunc});
cuda_fn!(cuModuleGetGlobal_v2(dptr: *mut CUdeviceptr, bytes: *mut usize, hmod: CUmodule, name: *const c_char) -> CUresult, {dptr, bytes});
cuda_fn!(cuLinkCreate_v2(numOptions: c_uint, options: *mut CUjit_option, optionValues: *mut *mut c_void, stateOut: *mut CUlinkState) -> CUresult);
cuda_fn!(cuLinkAddData_v2(state: CUlinkState, type_: CUjitInputType, data: *mut c_void, size: usize, name: *const c_char, numOptions: c_uint, options: *mut CUjit_option, optionValues: *mut *mut c_void) -> CUresult);
cuda_fn!(cuLinkAddFile_v2(state: CUlinkState, type_: CUjitInputType, path: *const c_char, numOptions: c_uint, options: *mut CUjit_option, optionValues: *mut *mut c_void) -> CUresult);
cuda_fn!(cuLinkComplete(state: CUlinkState, cubinOut: *mut *mut c_void, sizeOut: *mut usize) -> CUresult, {sizeOut});
cuda_fn!(cuLinkDestroy(state: CUlinkState) -> CUresult);
cuda_fn!(cuModuleGetTexRef(pTexRef: *mut CUtexref, hmod: CUmodule, name: *const c_char) -> CUresult);
cuda_fn!(cuModuleGetSurfRef(pSurfRef: *mut CUsurfref, hmod: CUmodule, name: *const c_char) -> CUresult);
cuda_fn!(cuLibraryLoadData(library: *mut CUlibrary, code: *const c_void, jitOptions: *mut CUjit_option, jitOptionsValues: *mut *mut c_void, numJitOptions: c_uint, libraryOptions: *mut CUlibraryOption, libraryOptionValues: *mut *mut c_void, numLibraryOptions: c_uint) -> CUresult, {library});
cuda_fn!(cuLibraryLoadFromFile(library: *mut CUlibrary, fileName: *const c_char, jitOptions: *mut CUjit_option, jitOptionsValues: *mut *mut c_void, numJitOptions: c_uint, libraryOptions: *mut CUlibraryOption, libraryOptionValues: *mut *mut c_void, numLibraryOptions: c_uint) -> CUresult, {library});
cuda_fn!(cuLibraryUnload(library: CUlibrary) -> CUresult);
cuda_fn!(cuLibraryGetKernel(pKernel: *mut CUkernel, library: CUlibrary, name: *const c_char) -> CUresult, {pKernel});
cuda_fn!(cuLibraryGetModule(pMod: *mut CUmodule, library: CUlibrary) -> CUresult, {pMod});
cuda_fn!(cuKernelGetFunction(pFunc: *mut CUfunction, kernel: CUkernel) -> CUresult, {pFunc});
cuda_fn!(cuLibraryGetGlobal(dptr: *mut CUdeviceptr, bytes: *mut usize, library: CUlibrary, name: *const c_char) -> CUresult, {dptr, bytes});
cuda_fn!(cuLibraryGetManaged(dptr: *mut CUdeviceptr, bytes: *mut usize, library: CUlibrary, name: *const c_char) -> CUresult, {dptr, bytes});
cuda_fn!(cuLibraryGetUnifiedFunction(fptr: *mut *mut c_void, library: CUlibrary, symbol: *const c_char) -> CUresult);
cuda_fn!(cuKernelGetAttribute(pi: *mut c_int, attrib: CUfunction_attribute, kernel: CUkernel, dev: CUdevice) -> CUresult, {pi});
cuda_fn!(cuKernelSetAttribute(attrib: CUfunction_attribute, val: c_int, kernel: CUkernel, dev: CUdevice) -> CUresult);
cuda_fn!(cuKernelSetCacheConfig(kernel: CUkernel, config: CUfunc_cache, dev: CUdevice) -> CUresult);
cuda_fn!(cuMemGetInfo_v2(free: *mut usize, total: *mut usize) -> CUresult, {free, total});
cuda_fn!(cuMemAlloc_v2(dptr: *mut CUdeviceptr, bytesize: usize) -> CUresult, {dptr});
cuda_fn!(cuMemAllocPitch_v2(dptr: *mut CUdeviceptr, pPitch: *mut usize, WidthInBytes: usize, Height: usize, ElementSizeBytes: c_uint) -> CUresult, {dptr, pPitch});
cuda_fn!(cuMemFree_v2(dptr: CUdeviceptr) -> CUresult);
cuda_fn!(cuMemGetAddressRange_v2(pbase: *mut CUdeviceptr, psize: *mut usize, dptr: CUdeviceptr) -> CUresult, {pbase, psize});
cuda_fn!(cuMemAllocHost_v2(pp: *mut *mut c_void, bytesize: usize) -> CUresult);
cuda_fn!(cuMemFreeHost(p: *mut c_void) -> CUresult);
cuda_fn!(cuMemHostAlloc(pp: *mut *mut c_void, bytesize: usize, Flags: c_uint) -> CUresult);
cuda_fn!(cuMemHostGetDevicePointer_v2(pdptr: *mut CUdeviceptr, p: *mut c_void, Flags: c_uint) -> CUresult, {pdptr});
cuda_fn!(cuMemHostGetFlags(pFlags: *mut c_uint, p: *mut c_void) -> CUresult, {pFlags});
cuda_fn!(cuMemAllocManaged(dptr: *mut CUdeviceptr, bytesize: usize, flags: c_uint) -> CUresult, {dptr});
cuda_fn!(cuDeviceGetByPCIBusId(dev: *mut CUdevice, pciBusId: *const c_char) -> CUresult, {dev});
cuda_fn!(cuDeviceGetPCIBusId(pciBusId: *mut c_char, len: c_int, dev: CUdevice) -> CUresult, {pciBusId});
cuda_fn!(cuIpcGetEventHandle(pHandle: *mut CUipcEventHandle, event: CUevent) -> CUresult, {pHandle});
cuda_fn!(cuIpcOpenEventHandle(phEvent: *mut CUevent, handle: CUipcEventHandle) -> CUresult, {phEvent});
cuda_fn!(cuIpcGetMemHandle(pHandle: *mut CUipcMemHandle, dptr: CUdeviceptr) -> CUresult);
cuda_fn!(cuIpcOpenMemHandle_v2(pdptr: *mut CUdeviceptr, handle: CUipcMemHandle, Flags: c_uint) -> CUresult, {pdptr});
cuda_fn!(cuIpcCloseMemHandle(dptr: CUdeviceptr) -> CUresult);
cuda_fn!(cuMemHostRegister_v2(p: *mut c_void, bytesize: usize, Flags: c_uint) -> CUresult);
cuda_fn!(cuMemHostUnregister(p: *mut c_void) -> CUresult);
cuda_fn!(cuMemcpy(dst: CUdeviceptr, src: CUdeviceptr, ByteCount: usize) -> CUresult);
cuda_fn!(cuMemcpyPeer(dstDevice: CUdeviceptr, dstContext: CUcontext, srcDevice: CUdeviceptr, srcContext: CUcontext, ByteCount: usize) -> CUresult);
cuda_fn!(cuMemcpyHtoD_v2(dstDevice: CUdeviceptr, srcHost: *const c_void, ByteCount: usize) -> CUresult);
cuda_fn!(cuMemcpyDtoH_v2(dstHost: *mut c_void, srcDevice: CUdeviceptr, ByteCount: usize) -> CUresult);
cuda_fn!(cuMemcpyDtoD_v2(dstDevice: CUdeviceptr, srcDevice: CUdeviceptr, ByteCount: usize) -> CUresult);
cuda_fn!(cuMemcpyDtoA_v2(dstArray: CUarray, dstOffset: usize, srcDevice: CUdeviceptr, ByteCount: usize) -> CUresult);
cuda_fn!(cuMemcpyAtoD_v2(dstDevice: CUdeviceptr, srcArray: CUarray, srcOffset: usize, ByteCount: usize) -> CUresult);
cuda_fn!(cuMemcpyHtoA_v2(dstArray: CUarray, dstOffset: usize, srcHost: *const c_void, ByteCount: usize) -> CUresult);
cuda_fn!(cuMemcpyAtoH_v2(dstHost: *mut c_void, srcArray: CUarray, srcOffset: usize, ByteCount: usize) -> CUresult);
cuda_fn!(cuMemcpyAtoA_v2(dstArray: CUarray, dstOffset: usize, srcArray: CUarray, srcOffset: usize, ByteCount: usize) -> CUresult);
cuda_fn!(cuMemcpy2D_v2(pCopy: *const CUDA_MEMCPY2D) -> CUresult);
cuda_fn!(cuMemcpy2DUnaligned_v2(pCopy: *const CUDA_MEMCPY2D) -> CUresult);
cuda_fn!(cuMemcpy3D_v2(pCopy: *const CUDA_MEMCPY3D) -> CUresult);
cuda_fn!(cuMemcpy3DPeer(pCopy: *const CUDA_MEMCPY3D_PEER) -> CUresult);
cuda_fn!(cuMemcpyAsync(dst: CUdeviceptr, src: CUdeviceptr, ByteCount: usize, hStream: CUstream) -> CUresult);
cuda_fn!(cuMemcpyPeerAsync(dstDevice: CUdeviceptr, dstContext: CUcontext, srcDevice: CUdeviceptr, srcContext: CUcontext, ByteCount: usize, hStream: CUstream) -> CUresult);
cuda_fn!(cuMemcpyHtoDAsync_v2(dstDevice: CUdeviceptr, srcHost: *const c_void, ByteCount: usize, hStream: CUstream) -> CUresult);
cuda_fn!(cuMemcpyDtoHAsync_v2(dstHost: *mut c_void, srcDevice: CUdeviceptr, ByteCount: usize, hStream: CUstream) -> CUresult);
cuda_fn!(cuMemcpyDtoDAsync_v2(dstDevice: CUdeviceptr, srcDevice: CUdeviceptr, ByteCount: usize, hStream: CUstream) -> CUresult);
cuda_fn!(cuMemcpyHtoAAsync_v2(dstArray: CUarray, dstOffset: usize, srcHost: *const c_void, ByteCount: usize, hStream: CUstream) -> CUresult);
cuda_fn!(cuMemcpyAtoHAsync_v2(dstHost: *mut c_void, srcArray: CUarray, srcOffset: usize, ByteCount: usize, hStream: CUstream) -> CUresult);
cuda_fn!(cuMemcpy2DAsync_v2(pCopy: *const CUDA_MEMCPY2D, hStream: CUstream) -> CUresult);
cuda_fn!(cuMemcpy3DAsync_v2(pCopy: *const CUDA_MEMCPY3D, hStream: CUstream) -> CUresult);
cuda_fn!(cuMemcpy3DPeerAsync(pCopy: *const CUDA_MEMCPY3D_PEER, hStream: CUstream) -> CUresult);
cuda_fn!(cuMemsetD8_v2(dstDevice: CUdeviceptr, uc: c_uchar, N: usize) -> CUresult);
cuda_fn!(cuMemsetD16_v2(dstDevice: CUdeviceptr, us: c_ushort, N: usize) -> CUresult);
cuda_fn!(cuMemsetD32_v2(dstDevice: CUdeviceptr, ui: c_uint, N: usize) -> CUresult);
cuda_fn!(cuMemsetD2D8_v2(dstDevice: CUdeviceptr, dstPitch: usize, uc: c_uchar, Width: usize, Height: usize) -> CUresult);
cuda_fn!(cuMemsetD2D16_v2(dstDevice: CUdeviceptr, dstPitch: usize, us: c_ushort, Width: usize, Height: usize) -> CUresult);
cuda_fn!(cuMemsetD2D32_v2(dstDevice: CUdeviceptr, dstPitch: usize, ui: c_uint, Width: usize, Height: usize) -> CUresult);
cuda_fn!(cuMemsetD8Async(dstDevice: CUdeviceptr, uc: c_uchar, N: usize, hStream: CUstream) -> CUresult);
cuda_fn!(cuMemsetD16Async(dstDevice: CUdeviceptr, us: c_ushort, N: usize, hStream: CUstream) -> CUresult);
cuda_fn!(cuMemsetD32Async(dstDevice: CUdeviceptr, ui: c_uint, N: usize, hStream: CUstream) -> CUresult);
cuda_fn!(cuMemsetD2D8Async(dstDevice: CUdeviceptr, dstPitch: usize, uc: c_uchar, Width: usize, Height: usize, hStream: CUstream) -> CUresult);
cuda_fn!(cuMemsetD2D16Async(dstDevice: CUdeviceptr, dstPitch: usize, us: c_ushort, Width: usize, Height: usize, hStream: CUstream) -> CUresult);
cuda_fn!(cuMemsetD2D32Async(dstDevice: CUdeviceptr, dstPitch: usize, ui: c_uint, Width: usize, Height: usize, hStream: CUstream) -> CUresult);
cuda_fn!(cuArrayCreate_v2(pHandle: *mut CUarray, pAllocateArray: *const CUDA_ARRAY_DESCRIPTOR) -> CUresult);
cuda_fn!(cuArrayGetDescriptor_v2(pArrayDescriptor: *mut CUDA_ARRAY_DESCRIPTOR, hArray: CUarray) -> CUresult);
cuda_fn!(cuArrayGetSparseProperties(sparseProperties: *mut CUDA_ARRAY_SPARSE_PROPERTIES, array: CUarray) -> CUresult);
cuda_fn!(cuMipmappedArrayGetSparseProperties(sparseProperties: *mut CUDA_ARRAY_SPARSE_PROPERTIES, mipmap: CUmipmappedArray) -> CUresult);
cuda_fn!(cuArrayGetMemoryRequirements(memoryRequirements: *mut CUDA_ARRAY_MEMORY_REQUIREMENTS, array: CUarray, device: CUdevice) -> CUresult);
cuda_fn!(cuMipmappedArrayGetMemoryRequirements(memoryRequirements: *mut CUDA_ARRAY_MEMORY_REQUIREMENTS, mipmap: CUmipmappedArray, device: CUdevice) -> CUresult);
cuda_fn!(cuArrayGetPlane(pPlaneArray: *mut CUarray, hArray: CUarray, planeIdx: c_uint) -> CUresult);
cuda_fn!(cuArrayDestroy(hArray: CUarray) -> CUresult);
cuda_fn!(cuArray3DCreate_v2(pHandle: *mut CUarray, pAllocateArray: *const CUDA_ARRAY3D_DESCRIPTOR) -> CUresult);
cuda_fn!(cuArray3DGetDescriptor_v2(pArrayDescriptor: *mut CUDA_ARRAY3D_DESCRIPTOR, hArray: CUarray) -> CUresult);
cuda_fn!(cuMipmappedArrayCreate(pHandle: *mut CUmipmappedArray, pMipmappedArrayDesc: *const CUDA_ARRAY3D_DESCRIPTOR, numMipmapLevels: c_uint) -> CUresult);
cuda_fn!(cuMipmappedArrayGetLevel(pLevelArray: *mut CUarray, hMipmappedArray: CUmipmappedArray, level: c_uint) -> CUresult);
cuda_fn!(cuMipmappedArrayDestroy(hMipmappedArray: CUmipmappedArray) -> CUresult);
cuda_fn!(cuMemGetHandleForAddressRange(handle: *mut c_void, dptr: CUdeviceptr, size: usize, handleType: CUmemRangeHandleType, flags: c_ulonglong) -> CUresult);
cuda_fn!(cuMemAddressReserve(ptr: *mut CUdeviceptr, size: usize, alignment: usize, addr: CUdeviceptr, flags: c_ulonglong) -> CUresult, {ptr});
cuda_fn!(cuMemAddressFree(ptr: CUdeviceptr, size: usize) -> CUresult);
cuda_fn!(cuMemCreate(handle: *mut CUmemGenericAllocationHandle, size: usize, prop: *const CUmemAllocationProp, flags: c_ulonglong) -> CUresult);
cuda_fn!(cuMemRelease(handle: CUmemGenericAllocationHandle) -> CUresult);
cuda_fn!(cuMemMap(ptr: CUdeviceptr, size: usize, offset: usize, handle: CUmemGenericAllocationHandle, flags: c_ulonglong) -> CUresult);
cuda_fn!(cuMemMapArrayAsync(mapInfoList: *mut CUarrayMapInfo, count: c_uint, hStream: CUstream) -> CUresult);
cuda_fn!(cuMemUnmap(ptr: CUdeviceptr, size: usize) -> CUresult);
cuda_fn!(cuMemSetAccess(ptr: CUdeviceptr, size: usize, desc: *const CUmemAccessDesc, count: usize) -> CUresult);
cuda_fn!(cuMemGetAccess(flags: *mut c_ulonglong, location: *const CUmemLocation, ptr: CUdeviceptr) -> CUresult, {flags});
cuda_fn!(cuMemExportToShareableHandle(shareableHandle: *mut c_void, handle: CUmemGenericAllocationHandle, handleType: CUmemAllocationHandleType, flags: c_ulonglong) -> CUresult);
cuda_fn!(cuMemImportFromShareableHandle(handle: *mut CUmemGenericAllocationHandle, osHandle: *mut c_void, shHandleType: CUmemAllocationHandleType) -> CUresult);
cuda_fn!(cuMemGetAllocationGranularity(granularity: *mut usize, prop: *const CUmemAllocationProp, option: CUmemAllocationGranularity_flags) -> CUresult, {granularity});
cuda_fn!(cuMemGetAllocationPropertiesFromHandle(prop: *mut CUmemAllocationProp, handle: CUmemGenericAllocationHandle) -> CUresult);
cuda_fn!(cuMemRetainAllocationHandle(handle: *mut CUmemGenericAllocationHandle, addr: *mut c_void) -> CUresult);
cuda_fn!(cuMemFreeAsync(dptr: CUdeviceptr, hStream: CUstream) -> CUresult);
cuda_fn!(cuMemAllocAsync(dptr: *mut CUdeviceptr, bytesize: usize, hStream: CUstream) -> CUresult, {dptr});
cuda_fn!(cuMemPoolTrimTo(pool: CUmemoryPool, minBytesToKeep: usize) -> CUresult);
cuda_fn!(cuMemPoolSetAttribute(pool: CUmemoryPool, attr: CUmemPool_attribute, value: *mut c_void) -> CUresult);
cuda_fn!(cuMemPoolGetAttribute(pool: CUmemoryPool, attr: CUmemPool_attribute, value: *mut c_void) -> CUresult);
cuda_fn!(cuMemPoolSetAccess(pool: CUmemoryPool, map: *const CUmemAccessDesc, count: usize) -> CUresult);
cuda_fn!(cuMemPoolGetAccess(flags: *mut CUmemAccess_flags, memPool: CUmemoryPool, location: *mut CUmemLocation) -> CUresult);
cuda_fn!(cuMemPoolCreate(pool: *mut CUmemoryPool, poolProps: *const CUmemPoolProps) -> CUresult);
cuda_fn!(cuMemPoolDestroy(pool: CUmemoryPool) -> CUresult);
cuda_fn!(cuMemAllocFromPoolAsync(dptr: *mut CUdeviceptr, bytesize: usize, pool: CUmemoryPool, hStream: CUstream) -> CUresult, {dptr});
cuda_fn!(cuMemPoolExportToShareableHandle(handle_out: *mut c_void, pool: CUmemoryPool, handleType: CUmemAllocationHandleType, flags: c_ulonglong) -> CUresult);
cuda_fn!(cuMemPoolImportFromShareableHandle(pool_out: *mut CUmemoryPool, handle: *mut c_void, handleType: CUmemAllocationHandleType, flags: c_ulonglong) -> CUresult);
cuda_fn!(cuMemPoolExportPointer(shareData_out: *mut CUmemPoolPtrExportData, ptr: CUdeviceptr) -> CUresult);
cuda_fn!(cuMemPoolImportPointer(ptr_out: *mut CUdeviceptr, pool: CUmemoryPool, shareData: *mut CUmemPoolPtrExportData) -> CUresult, {ptr_out});
cuda_fn!(cuMulticastCreate(mcHandle: *mut CUmemGenericAllocationHandle, prop: *const CUmulticastObjectProp) -> CUresult);
cuda_fn!(cuMulticastAddDevice(mcHandle: CUmemGenericAllocationHandle, dev: CUdevice) -> CUresult);
cuda_fn!(cuMulticastBindMem(mcHandle: CUmemGenericAllocationHandle, mcOffset: usize, memHandle: CUmemGenericAllocationHandle, memOffset: usize, size: usize, flags: c_ulonglong) -> CUresult);
cuda_fn!(cuMulticastBindAddr(mcHandle: CUmemGenericAllocationHandle, mcOffset: usize, memptr: CUdeviceptr, size: usize, flags: c_ulonglong) -> CUresult);
cuda_fn!(cuMulticastUnbind(mcHandle: CUmemGenericAllocationHandle, dev: CUdevice, mcOffset: usize, size: usize) -> CUresult);
cuda_fn!(cuMulticastGetGranularity(granularity: *mut usize, prop: *const CUmulticastObjectProp, option: CUmulticastGranularity_flags) -> CUresult, {granularity});
cuda_fn!(cuPointerGetAttribute(data: *mut c_void, attribute: CUpointer_attribute, ptr: CUdeviceptr) -> CUresult);
cuda_fn!(cuMemPrefetchAsync(devPtr: CUdeviceptr, count: usize, dstDevice: CUdevice, hStream: CUstream) -> CUresult);
cuda_fn!(cuMemPrefetchAsync_v2(devPtr: CUdeviceptr, count: usize, location: CUmemLocation, flags: c_uint, hStream: CUstream) -> CUresult);
cuda_fn!(cuMemAdvise(devPtr: CUdeviceptr, count: usize, advice: CUmem_advise, device: CUdevice) -> CUresult);
cuda_fn!(cuMemAdvise_v2(devPtr: CUdeviceptr, count: usize, advice: CUmem_advise, location: CUmemLocation) -> CUresult);
cuda_fn!(cuMemRangeGetAttribute(data: *mut c_void, dataSize: usize, attribute: CUmem_range_attribute, devPtr: CUdeviceptr, count: usize) -> CUresult);
cuda_fn!(cuMemRangeGetAttributes(data: *mut *mut c_void, dataSizes: *mut usize, attributes: *mut CUmem_range_attribute, numAttributes: usize, devPtr: CUdeviceptr, count: usize) -> CUresult, {dataSizes});
cuda_fn!(cuPointerSetAttribute(value: *const c_void, attribute: CUpointer_attribute, ptr: CUdeviceptr) -> CUresult);
cuda_fn!(cuPointerGetAttributes(numAttributes: c_uint, attributes: *mut CUpointer_attribute, data: *mut *mut c_void, ptr: CUdeviceptr) -> CUresult);
cuda_fn!(cuStreamCreate(phStream: *mut CUstream, Flags: c_uint) -> CUresult, {phStream});
cuda_fn!(cuStreamCreateWithPriority(phStream: *mut CUstream, flags: c_uint, priority: c_int) -> CUresult, {phStream});
cuda_fn!(cuStreamGetPriority(hStream: CUstream, priority: *mut c_int) -> CUresult, {priority});
cuda_fn!(cuStreamGetFlags(hStream: CUstream, flags: *mut c_uint) -> CUresult, {flags});
cuda_fn!(cuStreamGetId(hStream: CUstream, streamId: *mut c_ulonglong) -> CUresult, {streamId});
cuda_fn!(cuStreamGetCtx(hStream: CUstream, pctx: *mut CUcontext) -> CUresult, {pctx});
cuda_fn!(cuStreamWaitEvent(hStream: CUstream, hEvent: CUevent, Flags: c_uint) -> CUresult);
cuda_fn!(cuStreamAddCallback(hStream: CUstream, callback: CUstreamCallback, userData: *mut c_void, flags: c_uint) -> CUresult);
cuda_fn!(cuStreamBeginCapture_v2(hStream: CUstream, mode: CUstreamCaptureMode) -> CUresult);
cuda_fn!(cuThreadExchangeStreamCaptureMode(mode: *mut CUstreamCaptureMode) -> CUresult, {mode});
cuda_fn!(cuStreamEndCapture(hStream: CUstream, phGraph: *mut CUgraph) -> CUresult, {phGraph});
cuda_fn!(cuStreamIsCapturing(hStream: CUstream, captureStatus: *mut CUstreamCaptureStatus) -> CUresult);
cuda_fn!(cuStreamGetCaptureInfo_v2(hStream: CUstream, captureStatus_out: *mut CUstreamCaptureStatus, id_out: *mut cuuint64_t, graph_out: *mut CUgraph, dependencies_out: *mut *const CUgraphNode, numDependencies_out: *mut usize) -> CUresult, {id_out, graph_out, numDependencies_out});
cuda_fn!(cuStreamUpdateCaptureDependencies(hStream: CUstream, dependencies: *mut CUgraphNode, numDependencies: usize, flags: c_uint) -> CUresult, {dependencies});
cuda_fn!(cuStreamAttachMemAsync(hStream: CUstream, dptr: CUdeviceptr, length: usize, flags: c_uint) -> CUresult);
cuda_fn!(cuStreamQuery(hStream: CUstream) -> CUresult);
cuda_fn!(cuStreamSynchronize(hStream: CUstream) -> CUresult);
cuda_fn!(cuStreamDestroy_v2(hStream: CUstream) -> CUresult);
cuda_fn!(cuStreamCopyAttributes(dst: CUstream, src: CUstream) -> CUresult);
cuda_fn!(cuStreamGetAttribute(hStream: CUstream, attr: CUstreamAttrID, value_out: *mut CUstreamAttrValue) -> CUresult);
cuda_fn!(cuStreamSetAttribute(hStream: CUstream, attr: CUstreamAttrID, value: *const CUstreamAttrValue) -> CUresult);
cuda_fn!(cuEventCreate(phEvent: *mut CUevent, Flags: c_uint) -> CUresult, {phEvent});
cuda_fn!(cuEventRecord(hEvent: CUevent, hStream: CUstream) -> CUresult);
cuda_fn!(cuEventRecordWithFlags(hEvent: CUevent, hStream: CUstream, flags: c_uint) -> CUresult);
cuda_fn!(cuEventQuery(hEvent: CUevent) -> CUresult);
cuda_fn!(cuEventSynchronize(hEvent: CUevent) -> CUresult);
cuda_fn!(cuEventDestroy_v2(hEvent: CUevent) -> CUresult);
cuda_fn!(cuEventElapsedTime(pMilliseconds: *mut f32, hStart: CUevent, hEnd: CUevent) -> CUresult, {pMilliseconds});
cuda_fn!(cuImportExternalMemory(extMem_out: *mut CUexternalMemory, memHandleDesc: *const CUDA_EXTERNAL_MEMORY_HANDLE_DESC) -> CUresult);
cuda_fn!(cuExternalMemoryGetMappedBuffer(devPtr: *mut CUdeviceptr, extMem: CUexternalMemory, bufferDesc: *const CUDA_EXTERNAL_MEMORY_BUFFER_DESC) -> CUresult, {devPtr});
cuda_fn!(cuExternalMemoryGetMappedMipmappedArray(mipmap: *mut CUmipmappedArray, extMem: CUexternalMemory, mipmapDesc: *const CUDA_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC) -> CUresult);
cuda_fn!(cuDestroyExternalMemory(extMem: CUexternalMemory) -> CUresult);
cuda_fn!(cuImportExternalSemaphore(extSem_out: *mut CUexternalSemaphore, semHandleDesc: *const CUDA_EXTERNAL_SEMAPHORE_HANDLE_DESC) -> CUresult);
cuda_fn!(cuSignalExternalSemaphoresAsync(extSemArray: *const CUexternalSemaphore, paramsArray: *const CUDA_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS, numExtSems: c_uint, stream: CUstream) -> CUresult);
cuda_fn!(cuWaitExternalSemaphoresAsync(extSemArray: *const CUexternalSemaphore, paramsArray: *const CUDA_EXTERNAL_SEMAPHORE_WAIT_PARAMS, numExtSems: c_uint, stream: CUstream) -> CUresult);
cuda_fn!(cuDestroyExternalSemaphore(extSem: CUexternalSemaphore) -> CUresult);
cuda_fn!(cuStreamWaitValue32_v2(stream: CUstream, addr: CUdeviceptr, value: cuuint32_t, flags: c_uint) -> CUresult);
cuda_fn!(cuStreamWaitValue64_v2(stream: CUstream, addr: CUdeviceptr, value: cuuint64_t, flags: c_uint) -> CUresult);
cuda_fn!(cuStreamWriteValue32_v2(stream: CUstream, addr: CUdeviceptr, value: cuuint32_t, flags: c_uint) -> CUresult);
cuda_fn!(cuStreamWriteValue64_v2(stream: CUstream, addr: CUdeviceptr, value: cuuint64_t, flags: c_uint) -> CUresult);
cuda_fn!(cuStreamBatchMemOp_v2(stream: CUstream, count: c_uint, paramArray: *mut CUstreamBatchMemOpParams, flags: c_uint) -> CUresult);
cuda_fn!(cuFuncGetAttribute(pi: *mut c_int, attrib: CUfunction_attribute, hfunc: CUfunction) -> CUresult, {pi});
cuda_fn!(cuFuncSetAttribute(hfunc: CUfunction, attrib: CUfunction_attribute, value: c_int) -> CUresult);
cuda_fn!(cuFuncSetCacheConfig(hfunc: CUfunction, config: CUfunc_cache) -> CUresult);
cuda_fn!(cuFuncSetSharedMemConfig(hfunc: CUfunction, config: CUsharedconfig) -> CUresult);
cuda_fn!(cuFuncGetModule(hmod: *mut CUmodule, hfunc: CUfunction) -> CUresult, {hmod});
cuda_fn!(cuLaunchKernel(f: CUfunction, gridDimX: c_uint, gridDimY: c_uint, gridDimZ: c_uint, blockDimX: c_uint, blockDimY: c_uint, blockDimZ: c_uint, sharedMemBytes: c_uint, hStream: CUstream, kernelParams: *mut *mut c_void, extra: *mut *mut c_void) -> CUresult);
cuda_fn!(cuLaunchKernelEx(config: *const CUlaunchConfig, f: CUfunction, kernelParams: *mut *mut c_void, extra: *mut *mut c_void) -> CUresult);
cuda_fn!(cuLaunchCooperativeKernel(f: CUfunction, gridDimX: c_uint, gridDimY: c_uint, gridDimZ: c_uint, blockDimX: c_uint, blockDimY: c_uint, blockDimZ: c_uint, sharedMemBytes: c_uint, hStream: CUstream, kernelParams: *mut *mut c_void) -> CUresult);
cuda_fn!(cuLaunchCooperativeKernelMultiDevice(launchParamsList: *mut CUDA_LAUNCH_PARAMS, numDevices: c_uint, flags: c_uint) -> CUresult);
cuda_fn!(cuLaunchHostFunc(hStream: CUstream, fn_: CUhostFn, userData: *mut c_void) -> CUresult);
cuda_fn!(cuFuncSetBlockShape(hfunc: CUfunction, x: c_int, y: c_int, z: c_int) -> CUresult);
cuda_fn!(cuFuncSetSharedSize(hfunc: CUfunction, bytes: c_uint) -> CUresult);
cuda_fn!(cuParamSetSize(hfunc: CUfunction, numbytes: c_uint) -> CUresult);
cuda_fn!(cuParamSeti(hfunc: CUfunction, offset: c_int, value: c_uint) -> CUresult);
cuda_fn!(cuParamSetf(hfunc: CUfunction, offset: c_int, value: f32) -> CUresult);
cuda_fn!(cuParamSetv(hfunc: CUfunction, offset: c_int, ptr: *mut c_void, numbytes: c_uint) -> CUresult);
cuda_fn!(cuLaunch(f: CUfunction) -> CUresult);
cuda_fn!(cuLaunchGrid(f: CUfunction, grid_width: c_int, grid_height: c_int) -> CUresult);
cuda_fn!(cuLaunchGridAsync(f: CUfunction, grid_width: c_int, grid_height: c_int, hStream: CUstream) -> CUresult);
cuda_fn!(cuParamSetTexRef(hfunc: CUfunction, texunit: c_int, hTexRef: CUtexref) -> CUresult);
cuda_fn!(cuGraphCreate(phGraph: *mut CUgraph, flags: c_uint) -> CUresult, {phGraph});
cuda_fn!(cuGraphAddKernelNode_v2(phGraphNode: *mut CUgraphNode, hGraph: CUgraph, dependencies: *const CUgraphNode, numDependencies: usize, nodeParams: *const CUDA_KERNEL_NODE_PARAMS) -> CUresult, {phGraphNode});
cuda_fn!(cuGraphKernelNodeGetParams_v2(hNode: CUgraphNode, nodeParams: *mut CUDA_KERNEL_NODE_PARAMS) -> CUresult);
cuda_fn!(cuGraphKernelNodeSetParams_v2(hNode: CUgraphNode, nodeParams: *const CUDA_KERNEL_NODE_PARAMS) -> CUresult);
cuda_fn!(cuGraphAddMemcpyNode(phGraphNode: *mut CUgraphNode, hGraph: CUgraph, dependencies: *const CUgraphNode, numDependencies: usize, copyParams: *const CUDA_MEMCPY3D, ctx: CUcontext) -> CUresult, {phGraphNode});
cuda_fn!(cuGraphMemcpyNodeGetParams(hNode: CUgraphNode, nodeParams: *mut CUDA_MEMCPY3D) -> CUresult);
cuda_fn!(cuGraphMemcpyNodeSetParams(hNode: CUgraphNode, nodeParams: *const CUDA_MEMCPY3D) -> CUresult);
cuda_fn!(cuGraphAddMemsetNode(phGraphNode: *mut CUgraphNode, hGraph: CUgraph, dependencies: *const CUgraphNode, numDependencies: usize, memsetParams: *const CUDA_MEMSET_NODE_PARAMS, ctx: CUcontext) -> CUresult, {phGraphNode});
cuda_fn!(cuGraphMemsetNodeGetParams(hNode: CUgraphNode, nodeParams: *mut CUDA_MEMSET_NODE_PARAMS) -> CUresult);
cuda_fn!(cuGraphMemsetNodeSetParams(hNode: CUgraphNode, nodeParams: *const CUDA_MEMSET_NODE_PARAMS) -> CUresult);
cuda_fn!(cuGraphAddHostNode(phGraphNode: *mut CUgraphNode, hGraph: CUgraph, dependencies: *const CUgraphNode, numDependencies: usize, nodeParams: *const CUDA_HOST_NODE_PARAMS) -> CUresult, {phGraphNode});
cuda_fn!(cuGraphHostNodeGetParams(hNode: CUgraphNode, nodeParams: *mut CUDA_HOST_NODE_PARAMS) -> CUresult);
cuda_fn!(cuGraphHostNodeSetParams(hNode: CUgraphNode, nodeParams: *const CUDA_HOST_NODE_PARAMS) -> CUresult);
cuda_fn!(cuGraphAddChildGraphNode(phGraphNode: *mut CUgraphNode, hGraph: CUgraph, dependencies: *const CUgraphNode, numDependencies: usize, childGraph: CUgraph) -> CUresult, {phGraphNode});
cuda_fn!(cuGraphChildGraphNodeGetGraph(hNode: CUgraphNode, phGraph: *mut CUgraph) -> CUresult, {phGraph});
cuda_fn!(cuGraphAddEmptyNode(phGraphNode: *mut CUgraphNode, hGraph: CUgraph, dependencies: *const CUgraphNode, numDependencies: usize) -> CUresult, {phGraphNode});
cuda_fn!(cuGraphAddEventRecordNode(phGraphNode: *mut CUgraphNode, hGraph: CUgraph, dependencies: *const CUgraphNode, numDependencies: usize, event: CUevent) -> CUresult, {phGraphNode});
cuda_fn!(cuGraphEventRecordNodeGetEvent(hNode: CUgraphNode, event_out: *mut CUevent) -> CUresult, {event_out});
cuda_fn!(cuGraphEventRecordNodeSetEvent(hNode: CUgraphNode, event: CUevent) -> CUresult);
cuda_fn!(cuGraphAddEventWaitNode(phGraphNode: *mut CUgraphNode, hGraph: CUgraph, dependencies: *const CUgraphNode, numDependencies: usize, event: CUevent) -> CUresult, {phGraphNode});
cuda_fn!(cuGraphEventWaitNodeGetEvent(hNode: CUgraphNode, event_out: *mut CUevent) -> CUresult, {event_out});
cuda_fn!(cuGraphEventWaitNodeSetEvent(hNode: CUgraphNode, event: CUevent) -> CUresult);
cuda_fn!(cuGraphAddExternalSemaphoresSignalNode(phGraphNode: *mut CUgraphNode, hGraph: CUgraph, dependencies: *const CUgraphNode, numDependencies: usize, nodeParams: *const CUDA_EXT_SEM_SIGNAL_NODE_PARAMS) -> CUresult, {phGraphNode});
cuda_fn!(cuGraphExternalSemaphoresSignalNodeGetParams(hNode: CUgraphNode, params_out: *mut CUDA_EXT_SEM_SIGNAL_NODE_PARAMS) -> CUresult);
cuda_fn!(cuGraphExternalSemaphoresSignalNodeSetParams(hNode: CUgraphNode, nodeParams: *const CUDA_EXT_SEM_SIGNAL_NODE_PARAMS) -> CUresult);
cuda_fn!(cuGraphAddExternalSemaphoresWaitNode(phGraphNode: *mut CUgraphNode, hGraph: CUgraph, dependencies: *const CUgraphNode, numDependencies: usize, nodeParams: *const CUDA_EXT_SEM_WAIT_NODE_PARAMS) -> CUresult, {phGraphNode});
cuda_fn!(cuGraphExternalSemaphoresWaitNodeGetParams(hNode: CUgraphNode, params_out: *mut CUDA_EXT_SEM_WAIT_NODE_PARAMS) -> CUresult);
cuda_fn!(cuGraphExternalSemaphoresWaitNodeSetParams(hNode: CUgraphNode, nodeParams: *const CUDA_EXT_SEM_WAIT_NODE_PARAMS) -> CUresult);
cuda_fn!(cuGraphAddBatchMemOpNode(phGraphNode: *mut CUgraphNode, hGraph: CUgraph, dependencies: *const CUgraphNode, numDependencies: usize, nodeParams: *const CUDA_BATCH_MEM_OP_NODE_PARAMS) -> CUresult, {phGraphNode});
cuda_fn!(cuGraphBatchMemOpNodeGetParams(hNode: CUgraphNode, nodeParams_out: *mut CUDA_BATCH_MEM_OP_NODE_PARAMS) -> CUresult);
cuda_fn!(cuGraphBatchMemOpNodeSetParams(hNode: CUgraphNode, nodeParams: *const CUDA_BATCH_MEM_OP_NODE_PARAMS) -> CUresult);
cuda_fn!(cuGraphExecBatchMemOpNodeSetParams(hGraphExec: CUgraphExec, hNode: CUgraphNode, nodeParams: *const CUDA_BATCH_MEM_OP_NODE_PARAMS) -> CUresult);
cuda_fn!(cuGraphAddMemAllocNode(phGraphNode: *mut CUgraphNode, hGraph: CUgraph, dependencies: *const CUgraphNode, numDependencies: usize, nodeParams: *mut CUDA_MEM_ALLOC_NODE_PARAMS) -> CUresult, {phGraphNode});
cuda_fn!(cuGraphMemAllocNodeGetParams(hNode: CUgraphNode, params_out: *mut CUDA_MEM_ALLOC_NODE_PARAMS) -> CUresult);
cuda_fn!(cuGraphAddMemFreeNode(phGraphNode: *mut CUgraphNode, hGraph: CUgraph, dependencies: *const CUgraphNode, numDependencies: usize, dptr: CUdeviceptr) -> CUresult, {phGraphNode});
cuda_fn!(cuGraphMemFreeNodeGetParams(hNode: CUgraphNode, dptr_out: *mut CUdeviceptr) -> CUresult, {dptr_out});
cuda_fn!(cuDeviceGraphMemTrim(device: CUdevice) -> CUresult);
cuda_fn!(cuDeviceGetGraphMemAttribute(device: CUdevice, attr: CUgraphMem_attribute, value: *mut c_void) -> CUresult);
cuda_fn!(cuDeviceSetGraphMemAttribute(device: CUdevice, attr: CUgraphMem_attribute, value: *mut c_void) -> CUresult);
cuda_fn!(cuGraphClone(phGraphClone: *mut CUgraph, originalGraph: CUgraph) -> CUresult, {phGraphClone});
cuda_fn!(cuGraphNodeFindInClone(phNode: *mut CUgraphNode, hOriginalNode: CUgraphNode, hClonedGraph: CUgraph) -> CUresult, {phNode});
cuda_fn!(cuGraphNodeGetType(hNode: CUgraphNode, type_: *mut CUgraphNodeType) -> CUresult);
cuda_fn!(cuGraphGetNodes(hGraph: CUgraph, nodes: *mut CUgraphNode, numNodes: *mut usize) -> CUresult, {nodes, numNodes});
cuda_fn!(cuGraphGetRootNodes(hGraph: CUgraph, rootNodes: *mut CUgraphNode, numRootNodes: *mut usize) -> CUresult, {rootNodes, numRootNodes});
cuda_fn!(cuGraphGetEdges(hGraph: CUgraph, from: *mut CUgraphNode, to: *mut CUgraphNode, numEdges: *mut usize) -> CUresult, {from, to, numEdges});
cuda_fn!(cuGraphNodeGetDependencies(hNode: CUgraphNode, dependencies: *mut CUgraphNode, numDependencies: *mut usize) -> CUresult, {dependencies, numDependencies});
cuda_fn!(cuGraphNodeGetDependentNodes(hNode: CUgraphNode, dependentNodes: *mut CUgraphNode, numDependentNodes: *mut usize) -> CUresult, {dependentNodes, numDependentNodes});
cuda_fn!(cuGraphAddDependencies(hGraph: CUgraph, from: *const CUgraphNode, to: *const CUgraphNode, numDependencies: usize) -> CUresult);
cuda_fn!(cuGraphRemoveDependencies(hGraph: CUgraph, from: *const CUgraphNode, to: *const CUgraphNode, numDependencies: usize) -> CUresult);
cuda_fn!(cuGraphDestroyNode(hNode: CUgraphNode) -> CUresult);
cuda_fn!(cuGraphInstantiateWithFlags(phGraphExec: *mut CUgraphExec, hGraph: CUgraph, flags: c_ulonglong) -> CUresult);
cuda_fn!(cuGraphInstantiateWithParams(phGraphExec: *mut CUgraphExec, hGraph: CUgraph, instantiateParams: *mut CUDA_GRAPH_INSTANTIATE_PARAMS) -> CUresult);
cuda_fn!(cuGraphExecGetFlags(hGraphExec: CUgraphExec, flags: *mut cuuint64_t) -> CUresult, {flags});
cuda_fn!(cuGraphExecKernelNodeSetParams_v2(hGraphExec: CUgraphExec, hNode: CUgraphNode, nodeParams: *const CUDA_KERNEL_NODE_PARAMS) -> CUresult);
cuda_fn!(cuGraphExecMemcpyNodeSetParams(hGraphExec: CUgraphExec, hNode: CUgraphNode, copyParams: *const CUDA_MEMCPY3D, ctx: CUcontext) -> CUresult);
cuda_fn!(cuGraphExecMemsetNodeSetParams(hGraphExec: CUgraphExec, hNode: CUgraphNode, memsetParams: *const CUDA_MEMSET_NODE_PARAMS, ctx: CUcontext) -> CUresult);
cuda_fn!(cuGraphExecHostNodeSetParams(hGraphExec: CUgraphExec, hNode: CUgraphNode, nodeParams: *const CUDA_HOST_NODE_PARAMS) -> CUresult);
cuda_fn!(cuGraphExecChildGraphNodeSetParams(hGraphExec: CUgraphExec, hNode: CUgraphNode, childGraph: CUgraph) -> CUresult);
cuda_fn!(cuGraphExecEventRecordNodeSetEvent(hGraphExec: CUgraphExec, hNode: CUgraphNode, event: CUevent) -> CUresult);
cuda_fn!(cuGraphExecEventWaitNodeSetEvent(hGraphExec: CUgraphExec, hNode: CUgraphNode, event: CUevent) -> CUresult);
cuda_fn!(cuGraphExecExternalSemaphoresSignalNodeSetParams(hGraphExec: CUgraphExec, hNode: CUgraphNode, nodeParams: *const CUDA_EXT_SEM_SIGNAL_NODE_PARAMS) -> CUresult);
cuda_fn!(cuGraphExecExternalSemaphoresWaitNodeSetParams(hGraphExec: CUgraphExec, hNode: CUgraphNode, nodeParams: *const CUDA_EXT_SEM_WAIT_NODE_PARAMS) -> CUresult);
cuda_fn!(cuGraphNodeSetEnabled(hGraphExec: CUgraphExec, hNode: CUgraphNode, isEnabled: c_uint) -> CUresult);
cuda_fn!(cuGraphNodeGetEnabled(hGraphExec: CUgraphExec, hNode: CUgraphNode, isEnabled: *mut c_uint) -> CUresult, {isEnabled});
cuda_fn!(cuGraphUpload(hGraphExec: CUgraphExec, hStream: CUstream) -> CUresult);
cuda_fn!(cuGraphLaunch(hGraphExec: CUgraphExec, hStream: CUstream) -> CUresult);
cuda_fn!(cuGraphExecDestroy(hGraphExec: CUgraphExec) -> CUresult);
cuda_fn!(cuGraphDestroy(hGraph: CUgraph) -> CUresult);
cuda_fn!(cuGraphExecUpdate_v2(hGraphExec: CUgraphExec, hGraph: CUgraph, resultInfo: *mut CUgraphExecUpdateResultInfo) -> CUresult);
cuda_fn!(cuGraphKernelNodeCopyAttributes(dst: CUgraphNode, src: CUgraphNode) -> CUresult);
cuda_fn!(cuGraphKernelNodeGetAttribute(hNode: CUgraphNode, attr: CUkernelNodeAttrID, value_out: *mut CUkernelNodeAttrValue) -> CUresult);
cuda_fn!(cuGraphKernelNodeSetAttribute(hNode: CUgraphNode, attr: CUkernelNodeAttrID, value: *const CUkernelNodeAttrValue) -> CUresult);
cuda_fn!(cuGraphDebugDotPrint(hGraph: CUgraph, path: *const c_char, flags: c_uint) -> CUresult);
cuda_fn!(cuUserObjectCreate(object_out: *mut CUuserObject, ptr: *mut c_void, destroy: CUhostFn, initialRefcount: c_uint, flags: c_uint) -> CUresult, {object_out});
cuda_fn!(cuUserObjectRetain(object: CUuserObject, count: c_uint) -> CUresult);
cuda_fn!(cuUserObjectRelease(object: CUuserObject, count: c_uint) -> CUresult);
cuda_fn!(cuGraphRetainUserObject(graph: CUgraph, object: CUuserObject, count: c_uint, flags: c_uint) -> CUresult);
cuda_fn!(cuGraphReleaseUserObject(graph: CUgraph, object: CUuserObject, count: c_uint) -> CUresult);
cuda_fn!(cuGraphAddNode(phGraphNode: *mut CUgraphNode, hGraph: CUgraph, dependencies: *const CUgraphNode, numDependencies: usize, nodeParams: *mut CUgraphNodeParams) -> CUresult, {phGraphNode});
cuda_fn!(cuGraphNodeSetParams(hNode: CUgraphNode, nodeParams: *mut CUgraphNodeParams)-> CUresult);
cuda_fn!(cuGraphExecNodeSetParams(hGraphExec: CUgraphExec, hNode: CUgraphNode, nodeParams: *mut CUgraphNodeParams) -> CUresult);
cuda_fn!(cuOccupancyMaxActiveBlocksPerMultiprocessor(numBlocks: *mut c_int, func: CUfunction, blockSize: c_int, dynamicSMemSize: usize) -> CUresult, {numBlocks});
cuda_fn!(cuOccupancyMaxActiveBlocksPerMultiprocessorWithFlags(numBlocks: *mut c_int, func: CUfunction, blockSize: c_int, dynamicSMemSize: usize, flags: c_uint) -> CUresult, {numBlocks});
cuda_fn!(cuOccupancyMaxPotentialBlockSize(minGridSize: *mut c_int, blockSize: *mut c_int, func: CUfunction, blockSizeToDynamicSMemSize: CUoccupancyB2DSize, dynamicSMemSize: usize, blockSizeLimit: c_int) -> CUresult, {minGridSize, blockSize});
cuda_fn!(cuOccupancyMaxPotentialBlockSizeWithFlags(minGridSize: *mut c_int, blockSize: *mut c_int, func: CUfunction, blockSizeToDynamicSMemSize: CUoccupancyB2DSize, dynamicSMemSize: usize, blockSizeLimit: c_int, flags: c_uint) -> CUresult, {minGridSize, blockSize});
cuda_fn!(cuOccupancyAvailableDynamicSMemPerBlock(dynamicSmemSize: *mut usize, func: CUfunction, numBlocks: c_int, blockSize: c_int) -> CUresult, {dynamicSmemSize});
cuda_fn!(cuOccupancyMaxPotentialClusterSize(clusterSize: *mut c_int, func: CUfunction, config: *const CUlaunchConfig) -> CUresult, {clusterSize});
cuda_fn!(cuOccupancyMaxActiveClusters(numClusters: *mut c_int, func: CUfunction, config: *const CUlaunchConfig) -> CUresult, {numClusters});
cuda_fn!(cuTexRefSetArray(hTexRef: CUtexref, hArray: CUarray, Flags: c_uint) -> CUresult);
cuda_fn!(cuTexRefSetMipmappedArray(hTexRef: CUtexref, hMipmappedArray: CUmipmappedArray, Flags: c_uint) -> CUresult);
cuda_fn!(cuTexRefSetAddress_v2(ByteOffset: *mut usize, hTexRef: CUtexref, dptr: CUdeviceptr, bytes: usize) -> CUresult, {ByteOffset});
cuda_fn!(cuTexRefSetAddress2D_v3(hTexRef: CUtexref, desc: *const CUDA_ARRAY_DESCRIPTOR, dptr: CUdeviceptr, Pitch: usize) -> CUresult);
cuda_fn!(cuTexRefSetFormat(hTexRef: CUtexref, fmt: CUarray_format, NumPackedComponents: c_int) -> CUresult);
cuda_fn!(cuTexRefSetAddressMode(hTexRef: CUtexref, dim: c_int, am: CUaddress_mode) -> CUresult);
cuda_fn!(cuTexRefSetFilterMode(hTexRef: CUtexref, fm: CUfilter_mode) -> CUresult);
cuda_fn!(cuTexRefSetMipmapFilterMode(hTexRef: CUtexref, fm: CUfilter_mode) -> CUresult);
cuda_fn!(cuTexRefSetMipmapLevelBias(hTexRef: CUtexref, bias: f32) -> CUresult);
cuda_fn!(cuTexRefSetMipmapLevelClamp(hTexRef: CUtexref, minMipmapLevelClamp: f32, maxMipmapLevelClamp: f32) -> CUresult);
cuda_fn!(cuTexRefSetMaxAnisotropy(hTexRef: CUtexref, maxAniso: c_uint) -> CUresult);
cuda_fn!(cuTexRefSetBorderColor(hTexRef: CUtexref, pBorderColor: *mut f32) -> CUresult, {pBorderColor});
cuda_fn!(cuTexRefSetFlags(hTexRef: CUtexref, Flags: c_uint) -> CUresult);
cuda_fn!(cuTexRefGetAddress_v2(pdptr: *mut CUdeviceptr, hTexRef: CUtexref) -> CUresult, {pdptr});
cuda_fn!(cuTexRefGetArray(phArray: *mut CUarray, hTexRef: CUtexref) -> CUresult);
cuda_fn!(cuTexRefGetMipmappedArray(phMipmappedArray: *mut CUmipmappedArray, hTexRef: CUtexref) -> CUresult);
cuda_fn!(cuTexRefGetAddressMode(pam: *mut CUaddress_mode, hTexRef: CUtexref, dim: c_int) -> CUresult);
cuda_fn!(cuTexRefGetFilterMode(pfm: *mut CUfilter_mode, hTexRef: CUtexref) -> CUresult);
cuda_fn!(cuTexRefGetFormat(pFormat: *mut CUarray_format, pNumChannels: *mut c_int, hTexRef: CUtexref) -> CUresult, {pNumChannels});
cuda_fn!(cuTexRefGetMipmapFilterMode(pfm: *mut CUfilter_mode, hTexRef: CUtexref) -> CUresult);
cuda_fn!(cuTexRefGetMipmapLevelBias(pbias: *mut f32, hTexRef: CUtexref) -> CUresult, {pbias});
cuda_fn!(cuTexRefGetMipmapLevelClamp(pminMipmapLevelClamp: *mut f32, pmaxMipmapLevelClamp: *mut f32, hTexRef: CUtexref) -> CUresult, {pminMipmapLevelClamp, pmaxMipmapLevelClamp});
cuda_fn!(cuTexRefGetMaxAnisotropy(pmaxAniso: *mut c_int, hTexRef: CUtexref) -> CUresult, {pmaxAniso});
cuda_fn!(cuTexRefGetBorderColor(pBorderColor: *mut f32, hTexRef: CUtexref) -> CUresult, {pBorderColor});
cuda_fn!(cuTexRefGetFlags(pFlags: *mut c_uint, hTexRef: CUtexref) -> CUresult, {pFlags});
cuda_fn!(cuTexRefCreate(pTexRef: *mut CUtexref) -> CUresult);
cuda_fn!(cuTexRefDestroy(hTexRef: CUtexref) -> CUresult);
cuda_fn!(cuSurfRefSetArray(hSurfRef: CUsurfref, hArray: CUarray, Flags: c_uint) -> CUresult);
cuda_fn!(cuSurfRefGetArray(phArray: *mut CUarray, hSurfRef: CUsurfref) -> CUresult);
cuda_fn!(cuTexObjectCreate(pTexObject: *mut CUtexObject, pResDesc: *const CUDA_RESOURCE_DESC, pTexDesc: *const CUDA_TEXTURE_DESC, pResViewDesc: *const CUDA_RESOURCE_VIEW_DESC) -> CUresult, {pTexObject});
cuda_fn!(cuTexObjectDestroy(texObject: CUtexObject) -> CUresult);
cuda_fn!(cuTexObjectGetResourceDesc(pResDesc: *mut CUDA_RESOURCE_DESC, texObject: CUtexObject) -> CUresult);
cuda_fn!(cuTexObjectGetTextureDesc(pTexDesc: *mut CUDA_TEXTURE_DESC, texObject: CUtexObject) -> CUresult);
cuda_fn!(cuTexObjectGetResourceViewDesc(pResViewDesc: *mut CUDA_RESOURCE_VIEW_DESC, texObject: CUtexObject) -> CUresult);
cuda_fn!(cuSurfObjectCreate(pSurfObject: *mut CUsurfObject, pResDesc: *const CUDA_RESOURCE_DESC) -> CUresult);
cuda_fn!(cuSurfObjectDestroy(surfObject: CUsurfObject) -> CUresult);
cuda_fn!(cuSurfObjectGetResourceDesc(pResDesc: *mut CUDA_RESOURCE_DESC, surfObject: CUsurfObject) -> CUresult);
cuda_fn!(cuTensorMapEncodeTiled(tensorMap: *mut CUtensorMap, tensorDataType: CUtensorMapDataType, tensorRank: cuuint32_t, globalAddress: *mut c_void, globalDim: *const cuuint64_t, globalStrides: *const cuuint64_t, boxDim: *const cuuint32_t, elementStrides: *const cuuint32_t, interleave: CUtensorMapInterleave, swizzle: CUtensorMapSwizzle, l2Promotion: CUtensorMapL2promotion, oobFill: CUtensorMapFloatOOBfill) -> CUresult);
cuda_fn!(cuTensorMapEncodeIm2col(tensorMap: *mut CUtensorMap, tensorDataType: CUtensorMapDataType, tensorRank: cuuint32_t, globalAddress: *mut c_void, globalDim: *const cuuint64_t, globalStrides: *const cuuint64_t, pixelBoxLowerCorner: *const c_int, pixelBoxUpperCorner: *const c_int, channelsPerPixel: cuuint32_t, pixelsPerColumn: cuuint32_t, elementStrides: *const cuuint32_t, interleave: CUtensorMapInterleave, swizzle: CUtensorMapSwizzle, l2Promotion: CUtensorMapL2promotion, oobFill: CUtensorMapFloatOOBfill) -> CUresult);
cuda_fn!(cuTensorMapReplaceAddress(tensorMap: *mut CUtensorMap, globalAddress: *mut c_void) -> CUresult);
cuda_fn!(cuDeviceCanAccessPeer(canAccessPeer: *mut c_int, dev: CUdevice, peerDev: CUdevice) -> CUresult, {canAccessPeer});
cuda_fn!(cuCtxEnablePeerAccess(peerContext: CUcontext, Flags: c_uint) -> CUresult);
cuda_fn!(cuCtxDisablePeerAccess(peerContext: CUcontext) -> CUresult);
cuda_fn!(cuDeviceGetP2PAttribute(value: *mut c_int, attrib: CUdevice_P2PAttribute, srcDevice: CUdevice, dstDevice: CUdevice) -> CUresult, {value});
cuda_fn!(cuGraphicsUnregisterResource(resource: CUgraphicsResource) -> CUresult);
cuda_fn!(cuGraphicsSubResourceGetMappedArray(pArray: *mut CUarray, resource: CUgraphicsResource, arrayIndex: c_uint, mipLevel: c_uint) -> CUresult);
cuda_fn!(cuGraphicsResourceGetMappedMipmappedArray(pMipmappedArray: *mut CUmipmappedArray, resource: CUgraphicsResource) -> CUresult);
cuda_fn!(cuGraphicsResourceGetMappedPointer_v2(pDevPtr: *mut CUdeviceptr, pSize: *mut usize, resource: CUgraphicsResource) -> CUresult, {pDevPtr, pSize});
cuda_fn!(cuGraphicsResourceSetMapFlags_v2(resource: CUgraphicsResource, flags: c_uint) -> CUresult);
cuda_fn!(cuGraphicsMapResources(count: c_uint, resources: *mut CUgraphicsResource, hStream: CUstream) -> CUresult);
cuda_fn!(cuGraphicsUnmapResources(count: c_uint, resources: *mut CUgraphicsResource, hStream: CUstream) -> CUresult);
cuda_fn!(cuGetProcAddress_v2(symbol: *const c_char, pfn: *mut *mut c_void, cudaVersion: c_int, flags: cuuint64_t, symbolStatus: *mut CUdriverProcAddressQueryResult) -> CUresult);
cuda_fn!(cuCoredumpGetAttribute(attrib: CUcoredumpSettings, value: *mut c_void, size: *mut usize) -> CUresult, {size});
cuda_fn!(cuCoredumpGetAttributeGlobal(attrib: CUcoredumpSettings, value: *mut c_void, size: *mut usize) -> CUresult, {size});
cuda_fn!(cuCoredumpSetAttribute(attrib: CUcoredumpSettings, value: *mut c_void, size: *mut usize) -> CUresult, {size});
cuda_fn!(cuCoredumpSetAttributeGlobal(attrib: CUcoredumpSettings, value: *mut c_void, size: *mut usize) -> CUresult, {size});
cuda_fn!(cuGetExportTable(ppExportTable: *mut *const c_void, pExportTableId: *const CUuuid) -> CUresult);
cuda_fn!(cuProfilerInitialize(configFile: *const c_char, outputFile: *const c_char, outputMode: CUoutput_mode) -> CUresult);
cuda_fn!(cuProfilerStart() -> CUresult);
cuda_fn!(cuProfilerStop() -> CUresult);